export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const VIEW_VIDEOGAME_DETAIL = 'VIEW_VIDEOGAME_DETAIL';
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const SORT_BY_ALPHABET = 'SORT_BY_ALPHABET';
export const SORT_BY_RATING = 'SORT_BY_RATING';